// Embeds the repo's skills/ folder into src/skills.generated.ts so the add-on
// can install the skills without reading node_modules: `sv add` runs before
// svelte-grab is installed, so the package's skills/ may not exist yet.
// Also embeds the svelte-grab version (root package.json) the skills come
// from, recorded in the project's .svelte-grab-skills.json manifest.
// Run by `npm run build`; tests/sv-addon.test.ts fails when the files are stale.
/* global URL, process, console */
import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const skillsDir = fileURLToPath(new URL('../../../skills/', import.meta.url));
const rootPackage = fileURLToPath(new URL('../../../package.json', import.meta.url));
const outFile = fileURLToPath(new URL('../src/skills.generated.ts', import.meta.url));

/** Same order and shape as readSkillFiles() in src/utils/packaged-skills.ts. */
export function collectSkillFiles(dir) {
	const out = [];
	const skills = readdirSync(dir)
		.filter(
			(name) => statSync(join(dir, name)).isDirectory() && existsSync(join(dir, name, 'SKILL.md'))
		)
		.sort();
	for (const skill of skills) {
		const walk = (rel) => {
			for (const name of readdirSync(join(dir, rel)).sort()) {
				if (name.startsWith('.')) continue;
				const childRel = `${rel}/${name}`;
				if (statSync(join(dir, childRel)).isDirectory()) walk(childRel);
				else
					out.push({ skill, path: childRel, content: readFileSync(join(dir, childRel), 'utf-8') });
			}
		};
		walk(skill);
	}
	return out;
}

export function renderSkillsModule(files, version) {
	return [
		'// Generated by packages/sv-addon/scripts/embed-skills.mjs from skills/. Do not edit.',
		"import type { SkillFile } from '../../../src/cli/skills-plan.js';",
		'',
		'/** svelte-grab version the embedded skills come from (recorded in the skills manifest). */',
		`export const SKILLS_VERSION = ${JSON.stringify(version)};`,
		'',
		`export const SKILL_FILES: readonly SkillFile[] = ${JSON.stringify(files, null, '\t')};`,
		''
	].join('\n');
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
	const { version } = JSON.parse(readFileSync(rootPackage, 'utf-8'));
	writeFileSync(outFile, renderSkillsModule(collectSkillFiles(skillsDir), version), 'utf-8');
	console.log(`embedded skills -> ${outFile}`);
}
